// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_C2Dv8M4xzw2KxFGPE3q6pVFxW0QeSc',
    appId: '1:114897730859:web:ca443f5e09720b9ad4d96e',
    messagingSenderId: '114897730859',
    projectId: 'dzprg-135e0',
    authDomain: 'dzprg-135e0.firebaseapp.com',
    storageBucket: 'dzprg-135e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYko4vEv1Z_F7u7bt592uHcRnzRva8lg',
    appId: '1:114897730859:android:c7b970f9504d5da5d4d96e',
    messagingSenderId: '114897730859',
    projectId: 'dzprg-135e0',
    storageBucket: 'dzprg-135e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoUF_yyYuiYhjBPxDJc7-abp0dj1HapA',
    appId: '1:114897730859:ios:395d9598f3d8694ed4d96e',
    messagingSenderId: '114897730859',
    projectId: 'dzprg-135e0',
    storageBucket: 'dzprg-135e0.firebasestorage.app',
    iosBundleId: 'com.example.dz32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyoUF_yyYuiYhjBPxDJc7-abp0dj1HapA',
    appId: '1:114897730859:ios:395d9598f3d8694ed4d96e',
    messagingSenderId: '114897730859',
    projectId: 'dzprg-135e0',
    storageBucket: 'dzprg-135e0.firebasestorage.app',
    iosBundleId: 'com.example.dz32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_C2Dv8M4xzw2KxFGPE3q6pVFxW0QeSc',
    appId: '1:114897730859:web:388dcc199ed19c34d4d96e',
    messagingSenderId: '114897730859',
    projectId: 'dzprg-135e0',
    authDomain: 'dzprg-135e0.firebaseapp.com',
    storageBucket: 'dzprg-135e0.firebasestorage.app',
  );

}